version: "3.3"
services:
  backend:
    build:
      context: ${CODECOMP_DIR}/codecomp-backend
      dockerfile: Dockerfile
      # args:
      #   DEVELOPER_TOOLS: 1
    image: white105/codecomp-backend:dev
    networks: codecomppub0
    ports:
      - "127.0.0.1:9090:8080"
    volumes:
      - ${CODECOMP_DIR}/codecomp-backend:/opt/go/src/codecomp-backend
  codecomp:
    build:
      context: ${CODECOMP_DIR}/codecomp
      dockerfile: Dockerfile
      # args:
      #   DEVELOPER_TOOLS: 1
    image: white105/codecomp:dev
    ports:
      - "127.0.0.1:8080:8080"
      - "127.0.0.1:8443:8443"
    # this configuration requires manual refreshes
    environment:
      - SERVER=nginx
      - TLS_ENABLED=0
      - DEBUG_CONF=1
      - INSECURE_LISTEN_PORT=8080
      - API_BACKEND_PROTO=http
      - API_BACKEND_HOST=backend
      - API_BACKEND_PORT=8080
      - DEBUG_CONF=0
    # using nginx w/ manual refresh approach
    volumes:
      - ${CODECOMP_DIR}/codecomp/build:/var/www/app
    networks:
      codecomppub0:
    depends_on:
      - backend
networks:
  codecomppub0:
    # Use a custom driver
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.28.21.0/24
    driver_opts:
      com.docker.network.bridge.name: codecomppub0
